# Generated by Django 6.0.3 on 2026-08-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_bio_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user_type",
        ),
    ]
