# Generated by Django 6.0.3 on 2026-08-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='day_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
