# Generated by Django 6.0.3 on 2026-08-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_day_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='premium_user',
            field=models.BooleanField(default=False),
        ),
    ]
