# Generated by Django 6.0.3 on 2026-08-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("push", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PushLog",
        ),
    ]
