# Generated by Django 6.0.3 on 2026-08-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/%Y/%m/'),
        ),
    ]
