# Generated by Django 6.0.3 on 2026-08-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_alter_gallery_options_gallery_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='aid',
            field=models.TextField(blank=True, default='', help_text='Long, detailed one-line description of the entry.'),
        ),
    ]
