# Generated by Django 6.0.3 on 2026-08-09 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_journalentry_aid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='audio',
        ),
    ]
