# Generated by Django 6.0.7 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_chatsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='type',
            field=models.CharField(choices=[('text', 'Text')], default='text', max_length=10),
        ),
    ]
